#!/bin/bash

set -e
user="spidax"

# Do not do snapper backups
export SNAP_PAC_SKIP=y

GPG_KEY_ID="C30D3E7D1257494C"

# dotfiles_dir="$(
#     cd "$(dirname "$0")"
#     pwd
# )"
# cd "$dotfiles_dir"

is_chroot() {
    ! cmp -s /proc/1/mountinfo /proc/self/mountinfo
}

systemctl_enable() {
    echo "systemctl --user enable "$1""
    systemctl --user enable "$1"
}

# Installing missing Arch repo packages and setting up services
sudo bash -c "/home/$user/init.sh"

# Setting up ssh and gpg keys
# Optional for setting ssh key and git repository to apply changes
if [ $user == "spidax" ]; then
    yadm decrypt
    chmod 600 ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa.pub

    gpg --import-options restore,keep-ownertrust --import ~/.gnupg/private.gpg
    find "$HOME/.gnupg" -type f -not -path "*#*" -exec chmod 600 {} \;
    find "$HOME/.gnupg" -type d -exec chmod 700 {} \;

    eval $(keychain --agents 'ssh' --eval --quiet id_rsa)

    yadm remote set-url origin git@github.com:xadips/dots.git
fi

git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si --noconfirm --needed
paru -Rdd --noconfirm --nocheck --skipreview ffmpeg
paru -S --noconfirm --needed --nocheck --skipreview ttf-blex-nerd-font-git snapper-rollback rofi-lbonn-wayland waybar-hyprland-git vscodium-bin vscodium-bin-marketplace vscodium-bin-features grimblast-git wl-clip-persist-git youtube-music-bin obs-studio-tytan652 obs-gstreamer obs-vkcapture vkbasalt ventoy-bin proton-ge-custom-bin discord-canary-electron-bin discord-canary-update-skip-git
cd ..
rm -rf paru-bin
bash -c "/home/$user/.config/VSCodium/User/extension-install"

echo "==========================="
echo "Setting up user dotfiles..."
echo "==========================="

if is_chroot; then
    echo >&2 "=== Running in chroot, skipping user services..."
else
    echo ""
    echo "================================="
    echo "Enabling and starting services..."
    echo "================================="
    systemctl --user daemon-reload
    systemctl_enable "pipewire.service"
    systemctl_enable "pipewire-pulse.service"
    systemctl_enable "wireplumber.service"
    systemctl_enable "polkit-kde.service"
    systemctl_enable "udiskie.service"
    systemctl_enable "waybar.service"
fi

echo ""
echo "======================================="
echo "Finishing various user configuration..."
echo "======================================="

mkdir -p /home/$user/Pictures/screenshots

# if is_chroot; then
#     echo >&2 "=== Running in chroot, skipping GTK file chooser dialog configuration..."
# else
#     #echo "Configuring GTK file chooser dialog"
#     #gsettings set org.gtk.Settings.FileChooser sort-directories-first true
# fi

echo ""
echo "======================================="
echo "Done please reboot..."
echo "======================================="
