#!/bin/bash

set -e
user="spidax"

GPG_KEY_ID="C30D3E7D1257494C"

# dotfiles_dir="$(
#     cd "$(dirname "$0")"
#     pwd
# )"
# cd "$dotfiles_dir"

is_chroot() {
    ! cmp -s /proc/1/mountinfo /proc/self/mountinfo
}

systemctl_enable_start() {
    echo "systemctl --user enable --now "$1""
    systemctl --user enable --now "$1"
}

# Installing missing Arch repo packages
sudo pacman -Syu --noconfirm --needed snapper easyeffects inetutils xdg-utils xdg-user-dirs pipewire pipewire-pulse pipewire-alsa pipewire-jack pipewire-audio wireplumber mesa zsh-completions zsh-syntax-highlighting hyprland xorg-xwayland xdg-desktop-portal-hyprland thunar polkit-kde-agent qt5-wayland qt6-wayland rsync kitty neofetch snap-pac keychain kernel-modules-hook dunst ripgrep bat yt-dlp mpv gnupg firefox polkit-kde-agent zathura zathura-pdf-mupdf zathura-djvu udiskie hyprpaper

# Setting up ssh and gpg keys
yadm decrypt
chmod 600 ~/.ssh/id_rsa
chmod 600 ~/.ssh/id_rsa.pub

gpg --import-options restore,keep-ownertrust --import ~/.gnupg/private.gpg
find "$HOME/.gnupg" -type f -not -path "*#*" -exec chmod 600 {} \;
find "$HOME/.gnupg" -type d -exec chmod 700 {} \;

eval $(keychain --agents 'ssh,gpg' --eval --quiet id_rsa C30D3E7D1257494C)

yadm remote set-url origin git@github.com:xadips/dots.git

git clone https://aur.archlinux.org/paru-bin.git
cd paru-bin
makepkg -si --noconfirm --needed
paru -S --noconfirm --nocheck --skipreview ttf-blex-nerd-font-git snapper-rollback rofi-lbonn-wayland waybar-hyprland vscodium-bin vscodium-bin-marketplace vscodium-bin-features
cd ..
rm -rf paru-bin
sudo bash -c "/home/$user/init.sh"

echo "==========================="
echo "Setting up user dotfiles..."
echo "==========================="

if is_chroot; then
    echo >&2 "=== Running in chroot, skipping user services..."
else
    echo ""
    echo "================================="
    echo "Enabling and starting services..."
    echo "================================="
    systemctl --user daemon-reload
    systemctl_enable_start "pipewire.service"
    systemctl_enable_start "pipewire-pulse.service"
    systemctl_enable_start "wireplumber.service"
    systemctl_enable_start "polkit-kde.service"
    systemctl_enable_start "udiskie.service"
    systemctl_enable_start "waybar.service"
fi

echo ""
echo "======================================="
echo "Finishing various user configuration..."
echo "======================================="

# if is_chroot; then
#     echo >&2 "=== Running in chroot, skipping GTK file chooser dialog configuration..."
# else
#     #echo "Configuring GTK file chooser dialog"
#     #gsettings set org.gtk.Settings.FileChooser sort-directories-first true
# fi
