#!/bin/zsh

while :
do
	game_running=$(ps -aux | rg '[g]amescope' | wc -l)
	vol=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2}' | sed 's/\...//')
	if [ $game_running -eq "0" ] && [ $vol -ne "0" ]
	then
		wpctl set-volume @DEFAULT_SINK@ 0.5 
	fi
	sleep 5
done

