#!/bin/zsh

down() {
    wpctl set-volume @DEFAULT_SINK@ 5%-
    volume=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2}' | sed 's/.*\.//')
    dunstify -a "Volume" "Volume Down : $volume%" -r 2593 -u normal
}

up() {
    wpctl set-volume @DEFAULT_SINK@ 5%+ -l 1.0
    volume=$(wpctl get-volume @DEFAULT_SINK@ | awk '{print $2}' | sed 's/.*\.//')
    dunstify -a "Volume" "Volume Up : $volume" -r 2593 -u normal
}

mute() {
    [[ $(wpctl get-volume @DEFAULT_SINK@ | awk '{print $3}') == "[MUTED]" ]] && dunstify -a "Volume" "UNMUTED" -i audio-volume-high-symbolic -r 2593 -u normal || dunstify -a "Volume" "MUTED" -i audio-volume-muted-symbolic -r 2593 -u normal
    wpctl set-mute @DEFAULT_SINK@ toggle
}

case "$1" in
up) up ;;
down) down ;;
mute) mute ;;
esac
