#!/bin/zsh

alias bigf= 'find / -xdev -type f -size +500M' # display "big" files > 500M

# +----+
# | ls |
# +----+

alias ls='ls --color=auto'
alias lsl='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -a'
alias l='ls -CF'

# +----+
# | cp |
# +----+

alias cp='cp --reflink=auto -v'
alias mv='mv'
alias rm='rm'

# +----+
# | cd |
# +----+

alias ..='cd ..'

# +------+
# | grep |
# +------+

alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# +--------+
# | Neovim |
# +--------+

#alias vim='nvim'
#alias vi='nvim'
alias svim='sudoedit'
alias nvimclean='rm -I $HOME/.local/share/nvim/swap/* && rm -I $HOME/.local/share/nvim/undo/*' # clean nvim swap file
#alias nvimcleanuundo='rm -I $HOME/.local/share/nvim/undo/*'            # clean the vim undo

# git
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r' # display remote branch
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d"                                                                                                                                                                              # Delete local branch merged with master
alias gblog="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'" # git log for each branches
alias gsub="git submodule update --remote"                                                                                                                                                                                                                                     # pull submodules

alias ssh_server="ssh citrina"

warframe_cp() {
	wl-paste -t text -w sh -c 'v=$(cat); cmp -s <(xclip -selection clipboard -o)  <<< "$v" || xclip -selection clipboard <<< "$v"'
}

#alias sync_valheim_plugins="rsync -r --info=progress2 ~/.config/r2modmanPlus-local/Valheim/profiles/RimtiesNamai/BepInEx/plugins/* citrina:/var/docker/valheim/config/bepinex/plugins"
#alias sync_valheim_configs="rsync -r --info=progress2 ~/.config/r2modmanPlus-local/Valheim/profiles/RimtiesNamai/BepInEx/config/* citrina:/var/docker/valheim/config/bepinex"


#alias sync_spt_backend="rsync -r --info=progress2 ~/Downloads/games/mods/server_pack/* citrina:/var/docker/sptserver/user/mods"
#alias sync_spt_headless="rsync -r --info=progress2 ~/Downloads/games/mods/headless_mods/* citrina:/var/docker/spt-headless/BepInEx/plugins"
alias sync_spt_modsync="rsync --info=progress2 ~/Games/spt/modsync.jsonc citrina:/var/docker/sptserver/user/mods/Corter-ModSync/config.jsonc"
