#!/bin/bash

alias bigf= 'find / -xdev -type f -size +500M' # display "big" files > 500M

# +----+
# | ls |
# +----+

alias ls='ls --color=auto'
alias lsl='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -a'
alias l='ls -CF'

# +----+
# | cp |
# +----+

alias cp='cp --reflink=auto -v'
alias mv='mv'
alias rm='rm'

# +----+
# | cd |
# +----+

alias ..='cd ..'

# +------+
# | grep |
# +------+

alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# +--------+
# | Neovim |
# +--------+

#alias vim='nvim'
#alias vi='nvim'
alias svim='sudoedit'
alias nvimclean='rm -I $HOME/.local/share/nvim/swap/* && rm -I $HOME/.local/share/nvim/undo/*' # clean nvim swap file
#alias nvimcleanuundo='rm -I $HOME/.local/share/nvim/undo/*'            # clean the vim undo

# git
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r' # display remote branch
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d"                                                                                                                                                                              # Delete local branch merged with master
alias gblog="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'" # git log for each branches
alias gsub="git submodule update --remote"                                                                                                                                                                                                                                     # pull submodules

alias ssh_mif="ssh -i .ssh/id_rsa -L 5555:linux:3389 ricu6580@uosis.mif.vu.lt"
alias ssh_cluster="ssh ricu6580@cluster.mif.vu.lt"
alias ssh_kvm="ssh -p 42069 root@spidax.xyz"
alias ssh_kvm2="ssh -p 42069 root@node2.spidax.xyz"
#alias ssh_pi="TERM=xterm-256color && ssh pi@192.168.1.5"
alias ssh_server="ssh laimas@192.168.1.6 -p 9889"
alias bg_audio="wpctl set-volume @DEFAULT_SINK@ 1.8"
